In [159]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [160]:
cs_df = pd.read_csv("Train_data.csv")
cs_df

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,anomaly
3,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25187,0,tcp,exec,RSTO,0,0,0,0,0,0,...,7,0.03,0.06,0.00,0.00,0.00,0.00,1.00,1.00,anomaly
25188,0,tcp,ftp_data,SF,334,0,0,0,0,0,...,39,1.00,0.00,1.00,0.18,0.00,0.00,0.00,0.00,anomaly
25189,0,tcp,private,REJ,0,0,0,0,0,0,...,13,0.05,0.07,0.00,0.00,0.00,0.00,1.00,1.00,anomaly
25190,0,tcp,nnsp,S0,0,0,0,0,0,0,...,20,0.08,0.06,0.00,0.00,1.00,1.00,0.00,0.00,anomaly
25191,0,tcp,finger,S0,0,0,0,0,0,0,...,49,0.19,0.03,0.01,0.00,1.00,1.00,0.00,0.00,anomaly

Now we have to convert this class to 0 or 1 according to normalor anomaly so Machine can easily understand.

In [161]:
cs_df["class"]= cs_df["class"].map({"normal":1,"anomaly":0})
cs_df

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,1
1,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,1
2,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,0
3,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,1
4,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25187,0,tcp,exec,RSTO,0,0,0,0,0,0,...,7,0.03,0.06,0.00,0.00,0.00,0.00,1.00,1.00,0
25188,0,tcp,ftp_data,SF,334,0,0,0,0,0,...,39,1.00,0.00,1.00,0.18,0.00,0.00,0.00,0.00,0
25189,0,tcp,private,REJ,0,0,0,0,0,0,...,13,0.05,0.07,0.00,0.00,0.00,0.00,1.00,1.00,0
25190,0,tcp,nnsp,S0,0,0,0,0,0,0,...,20,0.08,0.06,0.00,0.00,1.00,1.00,0.00,0.00,0
25191,0,tcp,finger,S0,0,0,0,0,0,0,...,49,0.19,0.03,0.01,0.00,1.00,1.00,0.00,0.00,0

In [162]:
df_duplicate = cs_df[cs_df.duplicated()]
df_duplicate
# As their is no duplicate rows

Empty DataFrame
Columns: [duration, protocol_type, service, flag, src_bytes, dst_bytes, land, wrong_fragment, urgent, hot, num_failed_logins, logged_in, num_compromised, root_shell, su_attempted, num_root, num_file_creations, num_shells, num_access_files, num_outbound_cmds, is_host_login, is_guest_login, count, srv_count, serror_rate, srv_serror_rate, rerror_rate, srv_rerror_rate, same_srv_rate, diff_srv_rate, srv_diff_host_rate, dst_host_count, dst_host_srv_count, dst_host_same_srv_rate, dst_host_diff_srv_rate, dst_host_same_src_port_rate, dst_host_srv_diff_host_rate, dst_host_serror_rate, dst_host_srv_serror_rate, dst_host_rerror_rate, dst_host_srv_rerror_rate, class]
Index: []

[0 rows x 42 columns]

In [163]:
cs_df.isna().sum()
# Thier is no nan values

duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
su_attempted                   0
num_root                       0
num_file_creations             0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
srv_serror_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_count                 0
dst_host_srv_count             0
dst_host_same_srv_rate         0
dst_host_diff_srv_rate         0
dst_host_same_src_port_rate    0
dst_host_srv_diff_host_rate    0
dst_host_serror_rate           0
dst_host_srv_serror_rate       0
dst_host_rerror_rate           0
dst_host_srv_rerror_rate       0
class                          0
dtype: int64

In [164]:
cs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25192 entries, 0 to 25191
Data columns (total 42 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   duration                     25192 non-null  int64
 1   protocol_type                25192 non-null  object
 2   service                      25192 non-null  object
 3   flag                         25192 non-null  object
 4   src_bytes                    25192 non-null  int64
 5   dst_bytes                    25192 non-null  int64
 6   land                         25192 non-null  int64
 7   wrong_fragment               25192 non-null  int64
 8   urgent                       25192 non-null  int64
 9   hot                          25192 non-null  int64
 10  num_failed_logins            25192 non-null  int64
 11  logged_in                    25192 non-null  int64
 12  num_compromised              25192 non-null  int64
 13  root_shell                   25192 non-null  int64
 14  su_attempted                 25192 non-null  int64
 15  num_root                     25192 non-null  int64
 16  num_file_creations           25192 non-null  int64
 17  num_shells                   25192 non-null  int64
 18  num_access_files             25192 non-null  int64
 19  num_outbound_cmds            25192 non-null  int64
 20  is_host_login                25192 non-null  int64
 21  is_guest_login               25192 non-null  int64
 22  count                        25192 non-null  int64
 23  srv_count                    25192 non-null  int64
 24  serror_rate                  25192 non-null  float64
 25  srv_serror_rate              25192 non-null  float64
 26  rerror_rate                  25192 non-null  float64
 27  srv_rerror_rate              25192 non-null  float64
 28  same_srv_rate                25192 non-null  float64
 29  diff_srv_rate                25192 non-null  float64
 30  srv_diff_host_rate           25192 non-null  float64
 31  dst_host_count               25192 non-null  int64
 32  dst_host_srv_count           25192 non-null  int64
 33  dst_host_same_srv_rate       25192 non-null  float64
 34  dst_host_diff_srv_rate       25192 non-null  float64
 35  dst_host_same_src_port_rate  25192 non-null  float64
 36  dst_host_srv_diff_host_rate  25192 non-null  float64
 37  dst_host_serror_rate         25192 non-null  float64
 38  dst_host_srv_serror_rate     25192 non-null  float64
 39  dst_host_rerror_rate         25192 non-null  float64
 40  dst_host_srv_rerror_rate     25192 non-null  float64
 41  class                        25192 non-null  int64
dtypes: float64(15), int64(24), object(3)
memory usage: 8.1+ MB

In [165]:
cs_df.describe()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
count,25192.000000,2.519200e+04,2.519200e+04,25192.000000,25192.000000,25192.00000,25192.000000,25192.000000,25192.000000,25192.000000,...,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000
mean,305.054104,2.433063e+04,3.491847e+03,0.000079,0.023738,0.00004,0.198039,0.001191,0.394768,0.227850,...,115.063036,0.519791,0.082539,0.147453,0.031844,0.285800,0.279846,0.117800,0.118769,0.533860
std,2686.555640,2.410805e+06,8.883072e+04,0.008910,0.260221,0.00630,2.154202,0.045418,0.488811,10.417352,...,110.646850,0.448944,0.187191,0.308367,0.110575,0.445316,0.446075,0.305869,0.317333,0.498862
min,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,10.000000,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,4.400000e+01,0.000000e+00,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,61.000000,0.510000,0.030000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,0.000000,2.790000e+02,5.302500e+02,0.000000,0.000000,0.00000,0.000000,0.000000,1.000000,0.000000,...,255.000000,1.000000,0.070000,0.060000,0.020000,1.000000,1.000000,0.000000,0.000000,1.000000
max,42862.000000,3.817091e+08,5.151385e+06,1.000000,3.000000,1.00000,77.000000,4.000000,1.000000,884.000000,...,255.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [166]:
# Converting object type data type into numeric conversion
print(cs_df['protocol_type'].value_counts())
# print(cs_df[['service']].value_counts())
print(cs_df['service'].value_counts())
# cs_df[
dict1 = cs_df['service'].value_counts().sort_values(ascending=True)
dict1.keys()

protocol_type
tcp     20526
udp      3011
icmp     1655
Name: count, dtype: int64
service
http         8003
private      4351
domain_u     1820
smtp         1449
ftp_data     1396
             ...
urh_i           4
red_i           3
pm_dump         3
tim_i           2
http_8001       1
Name: count, Length: 66, dtype: int64

Index(['http_8001', 'tim_i', 'red_i', 'pm_dump', 'urh_i', 'shell', 'printer',
       'pop_2', 'remote_job', 'rje', 'X11', 'ntp_u', 'IRC', 'sql_net', 'pop_3',
       'ssh', 'nntp', 'echo', 'sunrpc', 'netbios_ssn', 'kshell', 'netbios_ns',
       'netstat', 'login', 'link', 'netbios_dgm', 'systat', 'mtp', 'ldap',
       'exec', 'klogin', 'name', 'hostnames', 'discard', 'daytime', 'vmnet',
       'gopher', 'domain', 'efs', 'csnet_ns', 'http_443', 'supdup', 'nnsp',
       'urp_i', 'ctf', 'iso_tsap', 'uucp_path', 'imap4', 'whois', 'bgp',
       'time', 'uucp', 'courier', 'Z39_50', 'auth', 'ftp', 'finger', 'telnet',
       'ecr_i', 'other', 'eco_i', 'ftp_data', 'smtp', 'domain_u', 'private',
       'http'],
      dtype='object', name='service')

In [167]:
dummy_df = pd.get_dummies(cs_df['protocol_type'],dtype=int,drop_first=True)
dummy_df1 = pd.get_dummies(cs_df['service'],dtype=int,drop_first=True)
dummy_df2 = pd.get_dummies(cs_df['flag'],dtype=int,drop_first=True)

In [168]:
dummy_df1.columns

Index(['X11', 'Z39_50', 'auth', 'bgp', 'courier', 'csnet_ns', 'ctf', 'daytime',
       'discard', 'domain', 'domain_u', 'echo', 'eco_i', 'ecr_i', 'efs',
       'exec', 'finger', 'ftp', 'ftp_data', 'gopher', 'hostnames', 'http',
       'http_443', 'http_8001', 'imap4', 'iso_tsap', 'klogin', 'kshell',
       'ldap', 'link', 'login', 'mtp', 'name', 'netbios_dgm', 'netbios_ns',
       'netbios_ssn', 'netstat', 'nnsp', 'nntp', 'ntp_u', 'other', 'pm_dump',
       'pop_2', 'pop_3', 'printer', 'private', 'red_i', 'remote_job', 'rje',
       'shell', 'smtp', 'sql_net', 'ssh', 'sunrpc', 'supdup', 'systat',
       'telnet', 'tim_i', 'time', 'urh_i', 'urp_i', 'uucp', 'uucp_path',
       'vmnet', 'whois'],
      dtype='object')

In [169]:
dummy_df2.drop(columns=['S3'])
dummy_df1.drop(columns = ['http_8001','tim_i','red_i','pm_dump','urh_i','shell', 'printer','pop_2', 'remote_job', 'rje', 'X11', 'ntp_u', 'sql_net'])

,Z39_50,auth,bgp,courier,csnet_ns,ctf,daytime,discard,domain,domain_u,...,sunrpc,supdup,systat,telnet,time,urp_i,uucp,uucp_path,vmnet,whois
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25187,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25188,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25189,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25190,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25191,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [170]:
cs_df = pd.concat([cs_df,dummy_df,dummy_df1,dummy_df2],axis=1)
cs_df

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,REJ,RSTO,RSTOS0,RSTR,S0,S1,S2,S3,SF,SH
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,udp,other,SF,146,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,tcp,private,S0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,tcp,http,SF,232,8153,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,tcp,http,SF,199,420,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25187,0,tcp,exec,RSTO,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
25188,0,tcp,ftp_data,SF,334,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
25189,0,tcp,private,REJ,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
25190,0,tcp,nnsp,S0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
25191,0,tcp,finger,S0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [171]:
cs_df = cs_df.iloc[:,:]
cs_df = cs_df.drop(columns= ["num_outbound_cmds","is_host_login",'protocol_type','service','flag'],axis=1)
cs_df

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,REJ,RSTO,RSTOS0,RSTR,S0,S1,S2,S3,SF,SH
0,0,491,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,146,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,232,8153,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4,0,199,420,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25187,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
25188,0,334,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
25189,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
25190,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
25191,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [172]:
cs_df1 = cs_df.copy()

Byy this data correlation I get to know which columns I should take and which I cannot.SO if correlation with 0.0 to -0.0, I take this as a no correlation withmytargeted vaue i.e class(predict cyber security risk)

In [191]:
print(cs_df1.corr(method = "spearman")['class'].sort_values(ascending=False))
# cs_df1.corr()['class'].sort_values(ascending=False)

class                   1.000000
SF                      0.756731
dst_bytes               0.752060
same_srv_rate           0.731782
src_bytes               0.710548
                          ...
srv_serror_rate        -0.629288
dst_host_serror_rate   -0.636460
S0                     -0.650227
serror_rate            -0.654099
diff_srv_rate          -0.671843
Name: class, Length: 114, dtype: float64

In [202]:
corr= cs_df1.corrwith(cs_df['class'])
low_corr = corr[(abs(corr) < 0.09) &  (abs(corr) > -0.09)].index
high_corr = corr[(abs(corr) > 0.09) |  (abs(corr) < -0.09)].index
print(len(low_corr))
len(high_corr)

83

31

In [203]:
cs_df1 = cs_df.drop(columns= low_corr)
cs_df1

,wrong_fragment,logged_in,count,serror_rate,srv_serror_rate,rerror_rate,srv_rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,...,domain_u,eco_i,ecr_i,http,private,smtp,REJ,RSTR,S0,SF
0,0,0,2,0.0,0.0,0.0,0.0,1.00,0.00,0.00,...,0,0,0,0,0,0,0,0,0,1
1,0,0,13,0.0,0.0,0.0,0.0,0.08,0.15,0.00,...,0,0,0,0,0,0,0,0,0,1
2,0,0,123,1.0,1.0,0.0,0.0,0.05,0.07,0.00,...,0,0,0,0,1,0,0,0,1,0
3,0,1,5,0.2,0.2,0.0,0.0,1.00,0.00,0.00,...,0,0,0,1,0,0,0,0,0,1
4,0,1,30,0.0,0.0,0.0,0.0,1.00,0.00,0.09,...,0,0,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25187,0,0,100,0.0,0.0,1.0,1.0,0.07,0.07,0.00,...,0,0,0,0,0,0,0,0,0,0
25188,0,1,1,0.0,0.0,0.0,0.0,1.00,0.00,0.00,...,0,0,0,0,0,0,0,0,0,1
25189,0,0,105,0.0,0.0,1.0,1.0,0.07,0.07,0.00,...,0,0,0,0,1,0,1,0,0,0
25190,0,0,129,1.0,1.0,0.0,0.0,0.14,0.06,0.00,...,0,0,0,0,0,0,0,0,1,0
25191,0,0,38,1.0,1.0,0.0,0.0,0.24,0.11,0.00,...,0,0,0,0,0,0,0,0,1,0

'num_root','num_compromised', 'root_shell', 'num_file_creations', 'num_shells','hot', 'dst_bytes', 'num_failed_logins', 'land', 'srv_count'

This are data which have no relation with class feature.

In [204]:
cs_df1.to_csv('cs2.csv')